### ISSUE TITLE
->insert($data) with objects

### ISSUE THREAD

**Issue by TCB13** [usmanhalalit/pixie#67]
Hello,

Is there any particular reason why at `->insert($data)` the `$data` variable can't be an object for single inserts?
Or better yet, it could accept arrays of objects or an object with multiple objects inside to be inserted.

Thank you.

**Comment by neoascetic** [comment]
Because dealing with associative arrays is simpler. How Pixie could get all properties of object need to be treated as column names and values? Passed object need to extend `ArrayObject` in this case. All this leads to additional complexity. It is better to Pixie's client to deal with all this cases and simply pass a raw associative array.

**Comment by usmanhalalit** [comment]
Because you can't iterate through an object, usually.

Btw, you can use something like this if you wish:

```PHP
$obj = new \stdClass;
$obj->key1 = 'value1';
$obj->key3 = 'value2';
QB::table('test')->insert((array) $obj);
```

**Comment by TCB13** [comment]
@usmanhalalit this is what I've been doing for some time now ;). Thanks for the feedback anyway.
